import { HotIcon } from '@/assets/icons';
import type {
  CommunityComment,
  CommunityItem,
  PopularCommunityItem,
} from '@/types/types.ts';

export const COMMUNITY_CATEGORIES = [
  { code: 'popular', label: '인기글', icon: HotIcon },
  { code: 'all', label: '전체' },
  { code: 'restaurant', label: '맛집' },
  { code: 'event', label: '동네행사' },
  { code: 'pet', label: '반려동물' },
  { code: 'exercise', label: '운동' },
  { code: 'life', label: '생활/편의' },
  { code: 'lost', label: '분실/실종' },
  { code: 'hospital', label: '병원/약국' },
  { code: 'concern', label: '고민/사연' },
  { code: 'friend', label: '동네친구' },
  { code: 'moving', label: '이사/시공' },
  { code: 'realty', label: '주거/부동산' },
  { code: 'education', label: '교육' },
  { code: 'hobby', label: '취미' },
  { code: 'incident', label: '동네사건사고' },
  { code: 'scenery', label: '동네풍경' },
  { code: 'beauty', label: '미용' },
  { code: 'parenting', label: '임신/육아' },
  { code: 'general', label: '일반' },
] as const;

export const COMMUNITY_ITEMS: CommunityItem[] = [
  {
    id: 1,
    title: '우리 동네에 새로 생긴 산책로를 소개해요',
    content: '날씨 좋은 날 가볍게 걷기 좋고 저녁 풍경도 정말 예뻐요.',
    category: '동네풍경',
    location: '역삼동',
    tags: '산책,야경,동네풍경',
    createdAtText: '1시간 전',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-walk/320/320',
  },
  {
    id: 2,
    title: '주말에 열리는 동네 플리마켓 같이 가실 분',
    content: '이번 주 토요일 오전부터 공원 앞 광장에서 열린다고 합니다.',
    category: '동네행사',
    location: '서초동',
    tags: '플리마켓,주말행사,이웃모임',
    createdAtText: '2시간 전',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-market/320/320',
  },
  {
    id: 3,
    title: '근처에서 발견한 분위기 좋은 카페',
    content: '조용해서 책 읽거나 작업하기 좋았어요. 디저트도 맛있습니다.',
    category: '맛집',
    location: '송도동',
    tags: '카페,디저트,작업공간',
    createdAtText: '3시간 전',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-cafe/320/320',
  },
  {
    id: 4,
    title: '잃어버린 강아지를 찾고 있습니다',
    content: '갈색 목줄을 하고 있는 흰색 소형견입니다. 제보 부탁드려요.',
    category: '분실/실종',
    location: '신림동',
    tags: '강아지,실종동물,제보',
    createdAtText: '5시간 전',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-dog/320/320',
  },
  {
    id: 5,
    title: '퇴근 후 함께 러닝하실 동네 친구 구해요',
    content: '평일 저녁 8시쯤 천천히 5km 정도 달리는 모임입니다.',
    category: '운동',
    location: '청담동',
    tags: '러닝,운동모임,동네친구',
    createdAtText: '7시간 전',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-running/320/320',
  },
  {
    id: 6,
    title: '아이와 함께 가기 좋은 동네 도서관',
    content: '유아 열람실이 넓고 주말 프로그램도 다양하게 운영하네요.',
    category: '임신/육아',
    location: '다산동',
    tags: '도서관,아이와함께,주말프로그램',
    createdAtText: '어제',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/community-library/320/320',
  },
];

export const COMMUNITY_COMMENTS: readonly CommunityComment[] = [
  {
    content: '누워있는 건가요?? 너무 안쓰럽네요.',
    createdAtText: '1일 전',
    id: 1,
    likeCount: 2,
    location: '역무동',
    nickname: '피넛버터',
    profileImageUrl: 'https://picsum.photos/seed/community-comment-1/72/72',
    replyCount: 1,
    replies: [
      {
        content:
          '전 날까지는 움직여서 오늘 밥준건데 오늘은 기운이 없어 보여요.',
        createdAtText: '21시간 전',
        id: 11,
        likeCount: 1,
        location: '매산로1가',
        nickname: '당당근',
        replyCount: 0,
      },
    ],
  },
  {
    content:
      '왜 이렇게 가여운 냥이와 댕이들이 많은지 마음만 착잡해지네요. 모두 행복해졌으면 좋겠어요.',
    createdAtText: '21시간 전',
    id: 2,
    likeCount: 1,
    location: '권선2동',
    nickname: '언제나크리스마스',
    profileImageUrl: 'https://picsum.photos/seed/community-comment-2/72/72',
    replyCount: 0,
  },
  {
    content: '제 말이요. 저기 높아서 너무 위험해 보여요.',
    createdAtText: '21시간 전',
    id: 3,
    likeCount: 1,
    location: '매산로1가',
    nickname: '당당근',
    replyCount: 0,
  },
  {
    content: '구조 방법이 없을까요?',
    createdAtText: '19시간 전',
    id: 4,
    likeCount: 1,
    location: '오목천동',
    nickname: '포로리아옹',
    replyCount: 0,
  },
];

export const POPULAR_COMMUNITY_ITEMS: readonly PopularCommunityItem[] = [
  {
    id: 101,
    title: '동물',
    metadata: '미추홀구 용현1,4동 · 취미 · 7일 전',
    tags: '동물,취미,이웃이야기',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-animal/240/240',
  },
  {
    id: 102,
    title: '**강아지 봉구 찾습니다**',
    metadata: '고양시 일산동구 고봉동 · 분실/실종 · 5일 전',
    tags: '강아지,실종동물,봉구',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-dog/240/240',
  },
  {
    id: 103,
    title: '광안리에 한달 살기 왔어요~',
    metadata: '수영구 광안제1동 · 동네풍경 · 6일 전',
    tags: '광안리,한달살기,동네풍경',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-beach/240/240',
  },
  {
    id: 104,
    title: '이게 뭐에쓰는 녀석일까요?',
    metadata: '청주시 흥덕구 봉명1동 · 일반 · 7일 전',
    tags: '궁금해요,정보공유,동네질문',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-question/240/240',
  },
  {
    id: 105,
    title: '안녕하세요 포항에 온지 얼마 안된 학생입니다',
    metadata: '포항시 남구 지곡동 · 맛집 · 7일 전',
    tags: '포항,맛집추천,동네정보',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-student/240/240',
  },
  {
    id: 106,
    title: '하늘이.. 반으로',
    metadata: '안산시 상록구 이동 · 동네풍경 · 7일 전',
    tags: '하늘,풍경,오늘의동네',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-sky/240/240',
  },
  {
    id: 107,
    title: '이게 뭘까요? ㅠㅠㅠㅠ',
    metadata: '미추홀구 도화동 · 고민/사연 · 8일 전',
    tags: '고민,궁금해요,이웃도움',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-mystery/240/240',
  },
  {
    id: 108,
    title: '이 친구 아시는 분 계신가요..',
    metadata: '용인시 처인구 역북동 · 반려동물 · 8일 전',
    tags: '반려동물,제보,이웃찾기',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-friend/240/240',
  },
  {
    id: 109,
    title: '길 가다가 애견미용실 있길래 봤....',
    metadata: '영등포구 당산제1동 · 동네풍경 · 8일 전',
    tags: '애견미용,강아지,동네풍경',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-shop/240/240',
  },
  {
    id: 110,
    title: '무슨 벌레인가요?...',
    metadata: '중구 남산1동 · 생활/편의 · 5일 전',
    tags: '벌레,생활정보,궁금해요',
    likeCount: 6,
    commentCount: 5,
    viewCount: 0,
    imageUrl: 'https://picsum.photos/seed/neighborhood-bug/240/240',
  },
];
