import { HotIcon } from '@/assets/icons';
import type { CommunityItem } from '@/types/types.ts';

export const COMMUNITY_CATEGORIES = [
  { code: 'popular', label: '인기글', icon: HotIcon },
  { code: 'all', label: '전체' },
  { code: 'restaurant', label: '맛집' },
  { code: 'event', label: '동네행사' },
  { code: 'pet', label: '반려동물' },
  { code: 'exercise', label: '운동' },
  { code: 'life', label: '생활/편의' },
  { code: 'lost', label: '분실/실종' },
  { code: 'hospital', label: '병원/약국' },
  { code: 'concern', label: '고민/사연' },
  { code: 'friend', label: '동네친구' },
  { code: 'moving', label: '이사/시공' },
  { code: 'realty', label: '주거/부동산' },
  { code: 'education', label: '교육' },
  { code: 'hobby', label: '취미' },
  { code: 'incident', label: '동네사건사고' },
  { code: 'scenery', label: '동네풍경' },
  { code: 'beauty', label: '미용' },
  { code: 'parenting', label: '임신/육아' },
  { code: 'general', label: '일반' },
] as const;

export const COMMUNITY_ITEMS: CommunityItem[] = [
  {
    id: 1,
    title: '우리 동네에 새로 생긴 산책로를 소개해요',
    content: '날씨 좋은 날 가볍게 걷기 좋고 저녁 풍경도 정말 예뻐요.',
    category: '동네풍경',
    location: '역삼동',
    createdAtText: '1시간 전',
    likeCount: 24,
    commentCount: 8,
    imageUrl: 'https://picsum.photos/seed/community-walk/320/320',
  },
  {
    id: 2,
    title: '주말에 열리는 동네 플리마켓 같이 가실 분',
    content: '이번 주 토요일 오전부터 공원 앞 광장에서 열린다고 합니다.',
    category: '동네행사',
    location: '서초동',
    createdAtText: '2시간 전',
    likeCount: 18,
    commentCount: 12,
    imageUrl: 'https://picsum.photos/seed/community-market/320/320',
  },
  {
    id: 3,
    title: '근처에서 발견한 분위기 좋은 카페',
    content: '조용해서 책 읽거나 작업하기 좋았어요. 디저트도 맛있습니다.',
    category: '맛집',
    location: '송도동',
    createdAtText: '3시간 전',
    likeCount: 31,
    commentCount: 6,
    imageUrl: 'https://picsum.photos/seed/community-cafe/320/320',
  },
  {
    id: 4,
    title: '잃어버린 강아지를 찾고 있습니다',
    content: '갈색 목줄을 하고 있는 흰색 소형견입니다. 제보 부탁드려요.',
    category: '분실/실종',
    location: '신림동',
    createdAtText: '5시간 전',
    likeCount: 47,
    commentCount: 19,
    imageUrl: 'https://picsum.photos/seed/community-dog/320/320',
  },
  {
    id: 5,
    title: '퇴근 후 함께 러닝하실 동네 친구 구해요',
    content: '평일 저녁 8시쯤 천천히 5km 정도 달리는 모임입니다.',
    category: '운동',
    location: '청담동',
    createdAtText: '7시간 전',
    likeCount: 15,
    commentCount: 22,
    imageUrl: 'https://picsum.photos/seed/community-running/320/320',
  },
  {
    id: 6,
    title: '아이와 함께 가기 좋은 동네 도서관',
    content: '유아 열람실이 넓고 주말 프로그램도 다양하게 운영하네요.',
    category: '임신/육아',
    location: '다산동',
    createdAtText: '어제',
    likeCount: 20,
    commentCount: 5,
    imageUrl: 'https://picsum.photos/seed/community-library/320/320',
  },
];
