import type {
  LocalProfileCategoryItem,
  LocalProfileDocumentGroup,
  LocalProfileItem,
  LocalProfileOptionItem,
  LocalProfileStoreInfo,
} from '@/types/types.ts';

export const LOCAL_PROFILE_CATEGORIES: LocalProfileCategoryItem[] = [
  { code: 'food', label: '음식' },
  { code: 'cafeDessert', label: '카페·디저트' },
  { code: 'beauty', label: '뷰티' },
  { code: 'hobby', label: '취미' },
  { code: 'hospitalPharmacy', label: '병원·약국' },
  { code: 'movingDelivery', label: '이사·용달' },
  { code: 'life', label: '생활' },
  { code: 'education', label: '교육' },
  { code: 'repair', label: '수리' },
  { code: 'exercise', label: '운동' },
  { code: 'childcare', label: '육아' },
  { code: 'pet', label: '반려동물' },
  { code: 'hairSalon', label: '미용실' },
  { code: 'cleaning', label: '청소' },
  { code: 'laundry', label: '세탁소' },
  { code: 'interiorConstruction', label: '인테리어시공' },
  { code: 'bungeoppang', label: '붕어빵' },
  { code: 'pollingPlace', label: '투표소' },
];

export const LOCAL_PROFILE_OPTIONS: LocalProfileOptionItem[] = [
  { code: 'coupon', label: '쿠폰' },
  { code: 'instantBooking', label: '바로예약' },
  { code: 'instantPayment', label: '바로결제' },
];

const LOCAL_PROFILE_DOCUMENT_GROUPS: LocalProfileDocumentGroup[] = [
  {
    title: '사업자등록증',
    rows: [
      { label: '사업자번호', value: '6072274800' },
      { label: '상호명', value: '노마진폰마트' },
      { label: '대표자명', value: '박종수' },
      {
        label: '소재지',
        value: '경기도 수원시 영통구 대학로 109 (이의동) 104호',
      },
    ],
  },
  {
    title: '통신서비스 인증',
    rows: [
      { label: '판매유형', value: '판매점' },
      { label: '유선 사전승낙서 URL', value: '자세히 보기' },
      { label: '무선 사전승낙서 URL', value: '자세히 보기' },
    ],
  },
];

const LOCAL_PROFILE_DOCUMENT = {
  documentGroups: LOCAL_PROFILE_DOCUMENT_GROUPS,
  documentLabel: '사업자등록증 및 기타 서류',
};

const LOCAL_PROFILE_BENEFIT = {
  benefitTitle: '단골혜택',
  benefitDescription:
    '단골 등록 고객님은 출장비 20퍼센트 할인(시공자재,공임 제외) 두번째 주문 부터는 출장비 면제',
};

const LOCAL_PROFILE_NOTICE = {
  notice:
    '매장 상황에 따라 운영 시간이 변동될 수 있으니 방문 전 전화 문의를 부탁드립니다.',
};

const LOCAL_PROFILE_COUPONS = {
  coupons: [
    {
      id: 1,
      title: '단골 특가시세표 확인',
      expiresAt: '2026-12-31',
    },
    {
      id: 2,
      title: 'S26시리즈 사전예약 할인',
      expiresAt: '2026-10-31',
    },
  ],
};

const LOCAL_PROFILE_PRICES = {
  prices: [
    {
      id: 1,
      title: '기본 출장비용',
      price: '20,000원~',
      description: '상담 방문 점검 등 기본 지역 출장비용입니다',
      isRepresentative: true,
    },
    {
      id: 2,
      title: '매입등,간접등 시공',
      price: '20,000원~',
      description:
        '개당 설치 가격이며 (제품 포함) 전원선 입선 필요시나 스위치 추가시 별도 문의 주세요',
      isRepresentative: true,
    },
    {
      id: 3,
      title: '누전 수리',
      price: '80,000원~',
      description: '전문 장비로 전기적 모든 문제를 해결 해 드립니다 이상 원인 진단수리',
      isRepresentative: true,
    },
    {
      id: 4,
      title: '실링팬 보강설치',
      price: '100,000원~',
      description:
        '보유하신 실링팬 보강 설치 (직구제품 포함, 에어라트론 추가비용 4만원)기본 비용입니다',
      isRepresentative: true,
    },
    {
      id: 5,
      title: '콘센트 교체',
      price: '30,000원~',
      description: '노후 콘센트와 스위치 교체 기본 비용입니다',
      isRepresentative: true,
    },
    {
      id: 6,
      title: '조명 교체',
      price: '40,000원~',
      description: '가정용 조명 교체 및 설치 기본 비용입니다',
      isRepresentative: true,
    },
  ],
};

const LOCAL_PROFILE_NEWS = {
  news: [
    {
      id: 1,
      title: '셀프인테리어 조명마감',
      content:
        '셀프 인테리어 현장의 조명 마감 작업을 진행했습니다. 기존 배선 상태를 점검하고 천장 마감재 손상 없이 깔끔하게 시공했습니다.',
      createdAtText: '약 17시간',
      favoriteCount: 0,
      commentCount: 2,
      inquiryCount: 0,
      imageUrl: 'https://picsum.photos/seed/store-news1/184/184',
      viewCount: 15,
      comments: [
        {
          id: 1,
          authorName: '전구요정',
          content: '거실 조명도 같은 방식으로 교체 가능한가요?',
          createdAt: '2026-07-26T08:30:00+09:00',
          profileImageUrl: 'https://picsum.photos/seed/news-comment1/76/76',
        },
        {
          id: 2,
          authorName: '영통이웃',
          content: '깔끔하게 시공된 것 같아요. 비용 문의드려요.',
          createdAt: '2026-07-26T10:20:00+09:00',
          profileImageUrl: 'https://picsum.photos/seed/news-comment2/76/76',
        },
      ],
    },
    {
      id: 2,
      title: '거실등 설치',
      content:
        '거실 메인 조명을 LED 등기구로 교체 설치했습니다. 밝기와 색온도를 공간에 맞춰 조정하고 안전하게 고정했습니다.',
      createdAtText: '약 17시간',
      favoriteCount: 1,
      commentCount: 0,
      inquiryCount: 0,
      imageUrl: 'https://picsum.photos/seed/store-news2/184/184',
      viewCount: 12,
    },
    {
      id: 3,
      title: '실링팬 보강설치',
      content:
        '실링팬 설치 전 천장 보강 작업을 진행했습니다. 제품 하중을 고려해 안전하게 보강하고 전원 연결까지 마무리했습니다.',
      createdAtText: '약 17시간',
      favoriteCount: 1,
      commentCount: 0,
      inquiryCount: 0,
      imageUrl: 'https://picsum.photos/seed/store-news3/184/184',
      viewCount: 9,
    },
    {
      id: 4,
      title: '콘센트 교체 작업',
      content:
        '노후 콘센트를 새 제품으로 교체했습니다. 접지 상태와 전원 공급 상태를 확인하고 사용 중 불편이 없도록 점검했습니다.',
      createdAtText: '약 1일',
      favoriteCount: 2,
      commentCount: 1,
      inquiryCount: 1,
      imageUrl: 'https://picsum.photos/seed/store-news4/184/184',
      viewCount: 21,
    },
  ],
};

const LOCAL_PROFILE_REVIEWS = {
  reviews: [
    {
      id: 1,
      authorName: '코스모스',
      authorRegionText: '충남 아산시 탕정면',
      certifiedCount: 21,
      createdAtText: '6일 전 작성',
      profileImageUrl: 'https://picsum.photos/seed/review-profile1/96/96',
      rating: 5.0,
      content:
        '예쁜 테디베어 해바라기 알게해주심도 감사한데요. 튼튼하게 잘 자란 모종 주셔서 감사해요. 게다가 꽃 잘 피우는 비료까지 주시구요. 크게 잘 자라겠 주시는데 가격도 아기모종값으로 엄청 착하게 주시니 황송합니다. 잘 키울게요. 고맙습니다.',
      helpfulCount: 0,
      imageUrls: [
        'https://picsum.photos/seed/review1-image1/328/328',
        'https://picsum.photos/seed/review1-image2/328/328',
      ],
      reply: {
        createdAtText: '6일 전',
        content: '친절한 후기 감사드립니다. 예쁘게 키우세요^^',
      },
    },
    {
      id: 2,
      authorName: '초코맘',
      authorRegionText: '경기 수원시 장안구 연무동',
      certifiedCount: 28,
      createdAtText: '22일 전 작성',
      profileImageUrl: 'https://picsum.photos/seed/review-profile2/96/96',
      rating: 3.0,
      content:
        '사장님께서직접배달까지해주셔서넘감사하고 넘싱싱하고 당도 도적당하고 넘맛있어요 제가차가없다하시니 제가있는곳까지와주셨습니다 너무나도 감사합니다',
      helpfulCount: 1,
      reply: {
        createdAtText: '22일 전',
        content:
          '감사합니다 ~~맛있게 드셨다니 저도 기쁩니다. 친절한 후기 감사드립니다^^',
      },
    },
    {
      id: 3,
      authorName: 'soo',
      authorRegionText: '경기 수원시 권선구 권선1동',
      certifiedCount: 26,
      createdAtText: '약 1개월 전 작성',
      profileImageUrl: 'https://picsum.photos/seed/review-profile3/96/96',
      rating: 4.5,
      content:
        '테디베어해바라기 모종. 넘튼실하고 이뻐요 꽃피면. 사진ㅇㅎ 올려드릴게요',
      helpfulCount: 0,
      imageUrls: ['https://picsum.photos/seed/review3-image1/328/328'],
      reply: {
        createdAtText: '1개월 전',
        content: '잘 키워서 풍성한 꽃 보시길 바랄게요. 후기 감사합니다^^',
      },
    },
  ],
};

const LOCAL_PROFILE_STORE_INFO: { storeInfo: LocalProfileStoreInfo } = {
  storeInfo: {
    addressSummary: '경기도 수원시 영통구 영통동',
    appLink: 'https://www.daangn.com',
    businessHours: {
      current: '10:00 - 22:00',
      daily: [
        '월 10:00 - 22:00',
        '화 10:00 - 22:00',
        '수 10:00 - 22:00',
        '목 10:00 - 22:00',
        '금 10:00 - 22:00',
        '토 10:00 - 22:00',
        '일 10:00 - 22:00',
      ],
      description: '매일',
    },
    contact: '0504-3043-6890',
    facilities:
      '1인실, 커플실, 샤워시설, 수원페이, 경기지역화폐, 예약, 지역화폐, 제로페이, 주차, 와이파이, 베리어프리',
    mapImageUrl: 'https://picsum.photos/seed/store-map/720/360',
    website: 'https://m.place.naver.com/place/123456789',
    addresses: [
      {
        label: '도로명',
        address: '경기도 수원시 영통구 영통로 135',
        addressDetail: '상가211호',
      },
      {
        label: '지번',
        address: '경기도 수원시 영통구 망포동 383-12',
        addressDetail: '상가211호',
      },
    ],
  },
};

export const LOCAL_PROFILE_ITEMS: LocalProfileItem[] = [
  {
    id: 1,
    name: '배스킨라빈스 수원경희대',
    category: '아이스크림',
    description:
      'We make people happy! 행복을 전하는 프리미엄 아이스크림 배스킨라빈스',
    rating: 4.8,
    reviewCount: 14,
    commentCount: 37,
    location: '영통동',
    regionText: '경기 수원시 영통구 영통동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store1/240/240',
    createdAt: '2025-10-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store1/240/240',
      'https://picsum.photos/seed/store1-detail1/240/240',
      'https://picsum.photos/seed/store1-detail2/240/240',
      'https://picsum.photos/seed/store1-detail3/240/240',
      'https://picsum.photos/seed/store1-detail4/240/240',
    ],
  },
  {
    id: 2,
    name: '스피드전기',
    category: '주택수리종합',
    description:
      '전기 고장 수리, 조명 교체, 콘센트·스위치·차단기 교체 및 전기 증설 등 출장 시공',
    rating: 4.0,
    reviewCount: 4,
    commentCount: 22,
    location: '지동',
    regionText: '경기 수원시 영통구 지동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store2/240/240',
    createdAt: '2025-09-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store2/240/240',
      'https://picsum.photos/seed/store2-detail1/240/240',
      'https://picsum.photos/seed/store2-detail2/240/240',
      'https://picsum.photos/seed/store2-detail3/240/240',
      'https://picsum.photos/seed/store2-detail4/240/240',
    ],
  },
  {
    id: 3,
    name: '노마진폰마트',
    category: '모바일기기',
    description: '최저가 휴대폰 판매 및 24시간 상담 가능',
    rating: 4.9,
    reviewCount: 327,
    commentCount: 1533,
    location: '이의동',
    regionText: '경기 수원시 영통구 이의동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store3/240/240',
    createdAt: '2025-08-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store3/240/240',
      'https://picsum.photos/seed/store3-detail1/240/240',
      'https://picsum.photos/seed/store3-detail2/240/240',
      'https://picsum.photos/seed/store3-detail3/240/240',
      'https://picsum.photos/seed/store3-detail4/240/240',
    ],
  },
  {
    id: 4,
    name: '동탄휴대폰성지 도매폰 5호점 반월점',
    category: '모바일기기',
    description: '맞춤 컨설팅과 합리적인 가격으로 최신 기종 판매',
    rating: 4.9,
    reviewCount: 225,
    commentCount: 243,
    location: '반월동',
    regionText: '경기 수원시 영통구 반월동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store4/240/240',
    createdAt: '2025-07-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store4/240/240',
      'https://picsum.photos/seed/store4-detail1/240/240',
      'https://picsum.photos/seed/store4-detail2/240/240',
      'https://picsum.photos/seed/store4-detail3/240/240',
      'https://picsum.photos/seed/store4-detail4/240/240',
    ],
  },
  {
    id: 5,
    name: '더제이엔씨',
    category: '통신판매',
    description: '휴대폰 도매센터, 번호이동·신규가입·기기변경 지원',
    rating: 4.9,
    reviewCount: 150,
    commentCount: 135,
    location: '권선동',
    regionText: '경기 수원시 영통구 권선동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store5/240/240',
    createdAt: '2025-06-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store5/240/240',
      'https://picsum.photos/seed/store5-detail1/240/240',
      'https://picsum.photos/seed/store5-detail2/240/240',
      'https://picsum.photos/seed/store5-detail3/240/240',
      'https://picsum.photos/seed/store5-detail4/240/240',
    ],
  },
  {
    id: 6,
    name: '휴대폰성지 옆커폰 수원 망포점',
    category: '모바일기기',
    description: '박리다매 및 공동구매 시스템으로 다양한 혜택 제공',
    rating: 4.8,
    reviewCount: 700,
    commentCount: 2224,
    location: '망포동',
    regionText: '경기 수원시 영통구 망포동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store6/240/240',
    createdAt: '2025-05-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store6/240/240',
      'https://picsum.photos/seed/store6-detail1/240/240',
      'https://picsum.photos/seed/store6-detail2/240/240',
      'https://picsum.photos/seed/store6-detail3/240/240',
      'https://picsum.photos/seed/store6-detail4/240/240',
    ],
  },
  {
    id: 7,
    name: '돼지설명서',
    category: '소고기 구이',
    description: '국내산 1+등급 암돼지 전문 구이집',
    rating: 4.8,
    reviewCount: 582,
    commentCount: 691,
    location: '영통동',
    regionText: '경기 수원시 영통구 영통동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store7/240/240',
    createdAt: '2025-04-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store7/240/240',
      'https://picsum.photos/seed/store7-detail1/240/240',
      'https://picsum.photos/seed/store7-detail2/240/240',
      'https://picsum.photos/seed/store7-detail3/240/240',
      'https://picsum.photos/seed/store7-detail4/240/240',
    ],
  },
  {
    id: 8,
    name: 'SKT PS&M 인계점',
    category: '모바일기기',
    description: 'SK텔레콤 공식 대리점, 인터넷·TV·휴대폰 가입 상담',
    rating: 4.9,
    reviewCount: 92,
    commentCount: 220,
    location: '인계동',
    regionText: '경기 수원시 영통구 인계동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store8/240/240',
    createdAt: '2025-03-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store8/240/240',
      'https://picsum.photos/seed/store8-detail1/240/240',
      'https://picsum.photos/seed/store8-detail2/240/240',
      'https://picsum.photos/seed/store8-detail3/240/240',
      'https://picsum.photos/seed/store8-detail4/240/240',
    ],
  },
  {
    id: 9,
    name: '정성 탑 에어컨 설치',
    category: '에어컨판매및이전설치',
    description: '가정용 스탠드·벽걸이 에어컨 설치 및 이전 전문',
    rating: 4.8,
    reviewCount: 555,
    commentCount: 2164,
    location: '상현동',
    regionText: '경기 수원시 영통구 상현동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store9/240/240',
    createdAt: '2025-02-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store9/240/240',
      'https://picsum.photos/seed/store9-detail1/240/240',
      'https://picsum.photos/seed/store9-detail2/240/240',
      'https://picsum.photos/seed/store9-detail3/240/240',
      'https://picsum.photos/seed/store9-detail4/240/240',
    ],
  },
  {
    id: 10,
    name: '친절한 용달. 용달 이사',
    category: '용달이사/용달화물',
    description: '개인용달 및 원룸·오피스텔 이사 전문',
    rating: 4.8,
    reviewCount: 1066,
    commentCount: 1144,
    location: '광교2동',
    regionText: '경기 수원시 영통구 광교2동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store10/240/240',
    createdAt: '2025-01-01',
    ...LOCAL_PROFILE_DOCUMENT,
    ...LOCAL_PROFILE_BENEFIT,
    ...LOCAL_PROFILE_NOTICE,
    ...LOCAL_PROFILE_PRICES,
    ...LOCAL_PROFILE_COUPONS,
    ...LOCAL_PROFILE_STORE_INFO,
    ...LOCAL_PROFILE_NEWS,
    ...LOCAL_PROFILE_REVIEWS,
    imageUrls: [
      'https://picsum.photos/seed/store10/240/240',
      'https://picsum.photos/seed/store10-detail1/240/240',
      'https://picsum.photos/seed/store10-detail2/240/240',
      'https://picsum.photos/seed/store10-detail3/240/240',
      'https://picsum.photos/seed/store10-detail4/240/240',
    ],
  },
];
