import type {
  LocalProfileCategoryItem,
  LocalProfileItem,
  LocalProfileOptionItem,
} from '@/types/types.ts';

export const LOCAL_PROFILE_CATEGORIES: LocalProfileCategoryItem[] = [
  { code: 'food', label: '음식' },
  { code: 'cafeDessert', label: '카페·디저트' },
  { code: 'beauty', label: '뷰티' },
  { code: 'hobby', label: '취미' },
  { code: 'hospitalPharmacy', label: '병원·약국' },
  { code: 'movingDelivery', label: '이사·용달' },
  { code: 'life', label: '생활' },
  { code: 'education', label: '교육' },
  { code: 'repair', label: '수리' },
  { code: 'exercise', label: '운동' },
  { code: 'childcare', label: '육아' },
  { code: 'pet', label: '반려동물' },
  { code: 'hairSalon', label: '미용실' },
  { code: 'cleaning', label: '청소' },
  { code: 'laundry', label: '세탁소' },
  { code: 'interiorConstruction', label: '인테리어시공' },
  { code: 'bungeoppang', label: '붕어빵' },
  { code: 'pollingPlace', label: '투표소' },
];

export const LOCAL_PROFILE_OPTIONS: LocalProfileOptionItem[] = [
  { code: 'coupon', label: '쿠폰' },
  { code: 'instantBooking', label: '바로예약' },
  { code: 'instantPayment', label: '바로결제' },
];

export const LOCAL_PROFILE_ITEMS: LocalProfileItem[] = [
  {
    id: 1,
    name: '배스킨라빈스 수원경희대',
    category: '아이스크림',
    description:
      'We make people happy! 행복을 전하는 프리미엄 아이스크림 배스킨라빈스',
    rating: 4.8,
    reviewCount: 14,
    commentCount: 37,
    location: '영통동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store1/240/240',
  },
  {
    id: 2,
    name: '스피드전기',
    category: '주택수리종합',
    description:
      '전기 고장 수리, 조명 교체, 콘센트·스위치·차단기 교체 및 전기 증설 등 출장 시공',
    rating: 4.0,
    reviewCount: 4,
    commentCount: 22,
    location: '지동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store2/240/240',
  },
  {
    id: 3,
    name: '노마진폰마트',
    category: '모바일기기',
    description: '최저가 휴대폰 판매 및 24시간 상담 가능',
    rating: 4.9,
    reviewCount: 327,
    commentCount: 1533,
    location: '이의동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store3/240/240',
  },
  {
    id: 4,
    name: '동탄휴대폰성지 도매폰 5호점 반월점',
    category: '모바일기기',
    description: '맞춤 컨설팅과 합리적인 가격으로 최신 기종 판매',
    rating: 4.9,
    reviewCount: 225,
    commentCount: 243,
    location: '반월동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store4/240/240',
  },
  {
    id: 5,
    name: '더제이엔씨',
    category: '통신판매',
    description: '휴대폰 도매센터, 번호이동·신규가입·기기변경 지원',
    rating: 4.9,
    reviewCount: 150,
    commentCount: 135,
    location: '권선동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store5/240/240',
  },
  {
    id: 6,
    name: '휴대폰성지 옆커폰 수원 망포점',
    category: '모바일기기',
    description: '박리다매 및 공동구매 시스템으로 다양한 혜택 제공',
    rating: 4.8,
    reviewCount: 700,
    commentCount: 2224,
    location: '망포동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store6/240/240',
  },
  {
    id: 7,
    name: '돼지설명서',
    category: '소고기 구이',
    description: '국내산 1+등급 암돼지 전문 구이집',
    rating: 4.8,
    reviewCount: 582,
    commentCount: 691,
    location: '영통동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store7/240/240',
  },
  {
    id: 8,
    name: 'SKT PS&M 인계점',
    category: '모바일기기',
    description: 'SK텔레콤 공식 대리점, 인터넷·TV·휴대폰 가입 상담',
    rating: 4.9,
    reviewCount: 92,
    commentCount: 220,
    location: '인계동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store8/240/240',
  },
  {
    id: 9,
    name: '정성 탑 에어컨 설치',
    category: '에어컨판매및이전설치',
    description: '가정용 스탠드·벽걸이 에어컨 설치 및 이전 전문',
    rating: 4.8,
    reviewCount: 555,
    commentCount: 2164,
    location: '상현동',
    coupon: true,
    thumbnail: 'https://picsum.photos/seed/store9/240/240',
  },
  {
    id: 10,
    name: '친절한 용달. 용달 이사',
    category: '용달이사/용달화물',
    description: '개인용달 및 원룸·오피스텔 이사 전문',
    rating: 4.8,
    reviewCount: 1066,
    commentCount: 1144,
    location: '광교2동',
    coupon: false,
    thumbnail: 'https://picsum.photos/seed/store10/240/240',
  },
];
